sudo: false
language: node_js
cache:
  yarn: true
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
  # - '0.12' Some scripts not working atm due to libraries not supporting this version
  # - '4' Same issues as 0.12
  # - '6' Not working atm due to Standard only supporting versions >= 8
  - '8'
  - '10'
  - '12'
env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
install: yarn
script: yarn validate
jobs:
  include:
  - stage: release
    node_js: '12'
    deploy:
      provider: script
      script: yarn test:update && npx codecov && npx semantic-release
      skip_cleanup: true
branches:
  only: master
